// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingSystem.Data;

#nullable disable

namespace VotingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104131825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VotingSystem.Models.Ballot", b =>
                {
                    b.Property<Guid>("BallotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BallotId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteId", "UserId")
                        .IsUnique();

                    b.ToTable("Ballots");
                });

            modelBuilder.Entity("VotingSystem.Models.BallotRanking", b =>
                {
                    b.Property<Guid>("BallotRankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RankNumber")
                        .HasColumnType("int");

                    b.HasKey("BallotRankingId");

                    b.HasIndex("OptionId");

                    b.HasIndex("BallotId", "OptionId")
                        .IsUnique();

                    b.HasIndex("BallotId", "RankNumber")
                        .IsUnique();

                    b.ToTable("BallotRankings");
                });

            modelBuilder.Entity("VotingSystem.Models.Option", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OptionId");

                    b.HasIndex("VoteId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("VotingSystem.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.Property<Guid>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WinningOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VoteId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("WinningOptionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("VotingSystem.Models.Ballot", b =>
                {
                    b.HasOne("VotingSystem.Models.User", "User")
                        .WithMany("Ballots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Vote", "Vote")
                        .WithMany("Ballots")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("VotingSystem.Models.BallotRanking", b =>
                {
                    b.HasOne("VotingSystem.Models.Ballot", "Ballot")
                        .WithMany("Rankings")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Option", "Option")
                        .WithMany("BallotRankings")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ballot");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("VotingSystem.Models.Option", b =>
                {
                    b.HasOne("VotingSystem.Models.Vote", "Vote")
                        .WithMany("Options")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.HasOne("VotingSystem.Models.User", "Creator")
                        .WithMany("CreatedVotes")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Option", "WinningOption")
                        .WithMany()
                        .HasForeignKey("WinningOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("WinningOption");
                });

            modelBuilder.Entity("VotingSystem.Models.Ballot", b =>
                {
                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("VotingSystem.Models.Option", b =>
                {
                    b.Navigation("BallotRankings");
                });

            modelBuilder.Entity("VotingSystem.Models.User", b =>
                {
                    b.Navigation("Ballots");

                    b.Navigation("CreatedVotes");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.Navigation("Ballots");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
